; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mina32 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=M32I

@addr = global i8* null

define void @test_blockaddress() nounwind {
; M32I-LABEL: test_blockaddress:
; M32I:       ; %bb.0:
; M32I-NEXT:    addi sp, sp, -4
; M32I-NEXT:    st r14, [sp, 0]
; M32I-NEXT:    addi r14, sp, 4
; M32I-NEXT:    movu r0, %hi(addr)
; M32I-NEXT:    movl r0, %lo(addr)
; M32I-NEXT:    movu r1, %hi(.Ltmp0)
; M32I-NEXT:    movl r1, %lo(.Ltmp0)
; M32I-NEXT:    st r1, [r0, 0]
; M32I-NEXT:    ld r0, [r0, 0]
; M32I-NEXT:    rbra r0, 0
; M32I-NEXT:  .Ltmp0: ; Block address taken
; M32I-NEXT:  .LBB0_1: ; %block
; M32I-NEXT:    ld r14, [sp, 0]
; M32I-NEXT:    addi sp, sp, 4
; M32I-NEXT:    ret
  store volatile i8* blockaddress(@test_blockaddress, %block), i8** @addr
  %val = load volatile i8*, i8** @addr
  indirectbr i8* %val, [label %block]

block:
  ret void
}
