; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mina32 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=M32I

define i8 @sext_i1_to_i8(i1 %a) {
; M32I-LABEL: sext_i1_to_i8:
; M32I:       ; %bb.0:
; M32I-NEXT:    andi $r0, $r0, 1
; M32I-NEXT:    movi $r1, 0
; M32I-NEXT:    sub $r0, $r1, $r0
; M32I-NEXT:    ret
  %1 = sext i1 %a to i8
  ret i8 %1
}

define i16 @sext_i1_to_i16(i1 %a) {
; M32I-LABEL: sext_i1_to_i16:
; M32I:       ; %bb.0:
; M32I-NEXT:    andi $r0, $r0, 1
; M32I-NEXT:    movi $r1, 0
; M32I-NEXT:    sub $r0, $r1, $r0
; M32I-NEXT:    ret
  %1 = sext i1 %a to i16
  ret i16 %1
}

define i32 @sext_i1_to_i32(i1 %a) {
; M32I-LABEL: sext_i1_to_i32:
; M32I:       ; %bb.0:
; M32I-NEXT:    andi $r0, $r0, 1
; M32I-NEXT:    movi $r1, 0
; M32I-NEXT:    sub $r0, $r1, $r0
; M32I-NEXT:    ret
  %1 = sext i1 %a to i32
  ret i32 %1
}

define i16 @sext_i8_to_i16(i8 %a) {
; M32I-LABEL: sext_i8_to_i16:
; M32I:       ; %bb.0:
; M32I-NEXT:    lsl $r0, $r0, 24
; M32I-NEXT:    asr $r0, $r0, 24
; M32I-NEXT:    ret
  %1 = sext i8 %a to i16
  ret i16 %1
}

define i32 @sext_i8_to_i32(i8 %a) {
; M32I-LABEL: sext_i8_to_i32:
; M32I:       ; %bb.0:
; M32I-NEXT:    lsl $r0, $r0, 24
; M32I-NEXT:    asr $r0, $r0, 24
; M32I-NEXT:    ret
  %1 = sext i8 %a to i32
  ret i32 %1
}

define i32 @sext_i16_to_i32(i16 %a) {
; M32I-LABEL: sext_i16_to_i32:
; M32I:       ; %bb.0:
; M32I-NEXT:    lsl $r0, $r0, 16
; M32I-NEXT:    asr $r0, $r0, 16
; M32I-NEXT:    ret
  %1 = sext i16 %a to i32
  ret i32 %1
}

define i8 @zext_i1_to_i8(i1 %a) {
; M32I-LABEL: zext_i1_to_i8:
; M32I:       ; %bb.0:
; M32I-NEXT:    andi $r0, $r0, 1
; M32I-NEXT:    ret
  %1 = zext i1 %a to i8
  ret i8 %1
}

define i16 @zext_i1_to_i16(i1 %a) {
; M32I-LABEL: zext_i1_to_i16:
; M32I:       ; %bb.0:
; M32I-NEXT:    andi $r0, $r0, 1
; M32I-NEXT:    ret
  %1 = zext i1 %a to i16
  ret i16 %1
}

define i32 @zext_i1_to_i32(i1 %a) {
; M32I-LABEL: zext_i1_to_i32:
; M32I:       ; %bb.0:
; M32I-NEXT:    andi $r0, $r0, 1
; M32I-NEXT:    ret
  %1 = zext i1 %a to i32
  ret i32 %1
}

define i16 @zext_i8_to_i16(i8 %a) {
; M32I-LABEL: zext_i8_to_i16:
; M32I:       ; %bb.0:
; M32I-NEXT:    andi $r0, $r0, 255
; M32I-NEXT:    ret
  %1 = zext i8 %a to i16
  ret i16 %1
}

define i32 @zext_i8_to_i32(i8 %a) {
; M32I-LABEL: zext_i8_to_i32:
; M32I:       ; %bb.0:
; M32I-NEXT:    andi $r0, $r0, 255
; M32I-NEXT:    ret
  %1 = zext i8 %a to i32
  ret i32 %1
}

define i32 @zext_i16_to_i32(i16 %a) {
; M32I-LABEL: zext_i16_to_i32:
; M32I:       ; %bb.0:
; M32I-NEXT:    movu $r1, 0
; M32I-NEXT:    movl $r1, 65535
; M32I-NEXT:    and $r0, $r0, $r1
; M32I-NEXT:    ret
  %1 = zext i16 %a to i32
  ret i32 %1
}

define i1 @trunc_i8_to_i1(i8 %a) {
; M32I-LABEL: trunc_i8_to_i1:
; M32I:       ; %bb.0:
; M32I-NEXT:    ret
  %1 = trunc i8 %a to i1
  ret i1 %1
}

define i1 @trunc_i16_to_i1(i16 %a) {
; M32I-LABEL: trunc_i16_to_i1:
; M32I:       ; %bb.0:
; M32I-NEXT:    ret
  %1 = trunc i16 %a to i1
  ret i1 %1
}

define i1 @trunc_i32_to_i1(i32 %a) {
; M32I-LABEL: trunc_i32_to_i1:
; M32I:       ; %bb.0:
; M32I-NEXT:    ret
  %1 = trunc i32 %a to i1
  ret i1 %1
}

define i8 @trunc_i16_to_i8(i16 %a) {
; M32I-LABEL: trunc_i16_to_i8:
; M32I:       ; %bb.0:
; M32I-NEXT:    ret
  %1 = trunc i16 %a to i8
  ret i8 %1
}

define i8 @trunc_i32_to_i8(i32 %a) {
; M32I-LABEL: trunc_i32_to_i8:
; M32I:       ; %bb.0:
; M32I-NEXT:    ret
  %1 = trunc i32 %a to i8
  ret i8 %1
}

define i16 @trunc_i32_to_i16(i32 %a) {
; M32I-LABEL: trunc_i32_to_i16:
; M32I:       ; %bb.0:
; M32I-NEXT:    ret
  %1 = trunc i32 %a to i16
  ret i16 %1
}
